language: cpp
compiler: gcc
dist: trusty
python: "3.5"
jdk: openjdk8

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - g++-6
            - llvm-6.0-dev
            - tree
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - tree -dl /usr/lib/llvm*

install:
  - mkdir build

script:
  - cd build && cmake .. && make

after_success:
  - echo "Yay! Your code compiled and runs fine."

after_failure:
  - echo "Uh-oh - something is wrong with your code!"
